draft: two party holder op mode
timewave-computer/covenants pull request #298
Opened 2024-07-01 17:46 UTC by bekauz

closes #252

2024-07-03 18:37 UTC, keyleu approved these changes

2024-07-03 20:41 UTC, stiiifff approved these changes

2024-07-03 20:48 UTC, stiiifff requested changes

2024-07-03 20:48 UTC, stiiifff commented on contracts/two-party-pol-covenant/src/contract.rs
I think the holder's address can be moved to the `clock_initial_queue` on line 100.

2024-07-04 13:18 UTC, bekauz commented on contracts/two-party-pol-covenant/src/contract.rs
good one, totally missed it

2024-07-04 13:30 UTC, merged